---
remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  "mid-senior level": false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: true
  temporary: false
  internship: true
  other: false
  volunteer: false

date:
  "all time": false
  month: true
  week: true
  "24 hours": true

positions:
  - Software Developer
  - Web Developer
  - Web Designer
  - FullStack Developer
  - Frontend Developer
  - Backend Developer

locations:
  - USA

distance: 100

companyBlacklist:
  - Noir
  - Crossover

titleBlacklist:
  - word1
  - word2
